### ISSUE TITLE
Slow processing

### ISSUE THREAD

**Issue by Miantanzeel** [markus-wa/convert-to-opus#1]
I test this project once but it seems it is slower than other converters, to the best of my knowledge using Total Audio Converter is best because it can easily convert almost any audio to WAV, MP3, OGG, WMA, APE, FLAC, MP4, AAC, MPC. A convenient batch option is available. 
For details go to link 
https://www.coolutils.com/TotalAudioConverter

**Comment by markus-wa** [comment]
Hi, this tool is not a converter, it's just a script that calls a converter 🙂 (opusenc by default, but you could adjust it to use different converters if you need).

As a sidenote opusenc is free, while that other tool seems to be paid.

If you're interested in using different converters with this script feel free to create a PR.
