### ISSUE TITLE
Error when trying to specify bitrate

### ISSUE THREAD

**Issue by peioe** [markus-wa/convert-to-opus#3]
Hi, I'm trying to use to_opus.py to convert flac to 144kbps opus and when I run this command:
python3 convert-to-opus/to_opus.py --opusenc-args "--bitrate 144" -s /mnt/source/ -t /mnt/dest/ -thr 6

I get this error:
opusenc: unrecognized option '--bitrate 144'

and the encoding fails obviously. Any idea what I'm doing wrong ?

Thanks

**Comment by markus-wa** [comment]
Hi @peioe 

Yeah I should probably document the `--opusenc-args` flag a bit better.

give this one a go 🙂 

	python3 to_opus.py -s tests/source/ -t x --opusenc-args "'--bitrate'" --opusenc-args 144

I will also add a shorthand `-a` for it to make it a bit less clumsy to use (soon™️)

**Comment by markus-wa** [comment]
Also I think I might make `128` the default, which is supposedly "pretty much transparent" (vs 64 used by `opusenc` with no `--bitrate` provided)

https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings&mobileaction=toggle_view_desktop

**Comment by peioe** [comment]
Thanks for the super fast reply :) That works much better indeed. I tried a few things but I couldn't figure it out, wouldn't hurt to add an example to the readme.

Thanks

**Comment by markus-wa** [comment]
just popped it in right now 😉 

https://github.com/markus-wa/convert-to-opus#to_opuspy

gonna leave this issue open until I add the `-a` shorthand though 😄

**Comment by markus-wa** [comment]
Added the `-a` shorthand (and a new `--exclude` / `-x` parameter)

**Comment by peioe** [comment]
Awesome :) I wanted to ask about excluding files. Can I exclude *.png ?

**Comment by markus-wa** [comment]
You can now that I've just changed the code to support python regexes in #5 :smile:  

https://docs.python.org/3/howto/regex.html

e.g. `--exclude '.+\.png'` (might need two `\\` depending on your shell)
